version: "3.9"
services:
  app:
    build: .
    container_name: tourist_rental_app
    volumes:
      - sqlite_data:/app/data   # сохраняем базу вне контейнера
    ports:
      - "8080:8080"             # если твой GUI/сервер слушает порт, меняй по необходимости
    environment:
      - QT_QPA_PLATFORM=xcb
      - QT_PLUGIN_PATH=/app/sqldrivers
      - XDG_DATA_HOME=/app/data

volumes:
  sqlite_data:
